CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS analytics;
GRANT ALL ON SCHEMA raw TO postgres;
GRANT ALL ON SCHEMA analytics TO postgres;
GRANT ALL ON ALL TABLES IN SCHEMA raw TO postgres;
GRANT ALL ON ALL TABLES IN SCHEMA analytics TO postgres;
